config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:create, :new, :show], except: :index do
    resources :doses, only: [:create, :new]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :show
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <%= f.input :photo, as: :file %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1283219/pexels-photo-1283219.jpeg?cs=srgb&dl=assorted-wine-bottles-1283219.jpg&fm=jpg);">
  <div class="container">
    <h1>Welcome to Momo's bar!</h1>
    <p>Discover a drink or create your own original drink!</p>
    <%= link_to "Add cocktail", new_cocktail_path, class: "btn btn-success"  %>
  </div>
</div>

<div class="cocktails">
  <% @cocktails.each do |cocktail| %>
    <% if cocktail.photo.attached? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, crop: :fill %>')">
        <%= cocktail.name %>
        <%= link_to "", cocktail_path(cocktail), class:"card-remove-link" %>
      </div>
    <% else %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?cs=srgb&dl=alcoholic-bar-beverage-blur-338713.jpg&fm=jpg)">
        <%= cocktail.name %>
        <%= link_to "", cocktail_path(cocktail), class:"card-remove-link" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="form">
  <h1>Add Cocktail</h1>
  <%= render 'form', cocktail: @cocktail %>
</div>

app/views/cocktails/show.html.erb
<div class="card-trip">
  <% if @cocktail.photo.attached? %>
    <%= cl_image_tag @cocktail.photo.key, height: 200, width: 300, crop: :fill %>
  <% else %>
    <img src="https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?cs=srgb&dl=alcoholic-bar-beverage-blur-338713.jpg&fm=jpg">
  <% end %>
  <div class="card-trip-infos">
    <div>
      <h2><%= @cocktail.name %></h2>
      <ul class="list-group">
        <% @cocktail.doses.each do |dose| %>
          <li class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
              <div class="dose-info">
                <%= dose.description %>
                <%= dose.ingredient.name %>
              </div>
              <div class="delete-dose">
                <%= link_to dose_path(dose), class: 'delete-dose', method: :delete, data: { confirm: "Remove #{dose.description} #{dose.ingredient.name}?" } do%>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
   <%= link_to "Add Dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <div class="form-inputs">
    <%= f.input :description %>
  </div>
  <div class="form-inputs">
    <%= f.association :ingredient %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/new.html.erb
<div class="form">
  <h1>Add Dose</h1>
  <%= render 'form', dose: @dose %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-dark navbar-expand-sm navbar-light navbar-lewagon sticky">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktail", new_cocktail_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>